\ Spike.fs

REQUIRE RENT.FS 
REQUIRE SORT.FS 
INIT-ORDERS  
5 9 81 ADD-ORDER   
3 7 142 ADD-ORDER  
0 5 103 ADD-ORDER  
6 9 74 ADD-ORDER   
ORDERS 4 SORT   
: .ORDER ( t d p -- print an order ) ROT . SWAP . . ; 
: .ORDERS #ORDERS @ 0 DO ORDERS I CELLS + @ DECODE-ORDER .ORDER CR LOOP ; 
CR .ORDERS 
BYE
