#! /usr/bin/awk -f

# compute maximum profit made out of sorted actions

BEGIN { profit = 0 }

{ if ($2 == "CASH") 
    cash($1) 
    else 
    rent($1,$3,$4) }

END { print profit }

function cash(time) {
    t = key(time)
    profit = max(plan[t], profit)
}

function rent(time,duration,price) {
    cash(time) 
    t = key(time + duration)
    plan[t] = max(profit + price, plan[t]) 
}

function key(t) {
    return(sprintf("%07d",t))
}

function max(a, b) {
    return a > b ? a : b
}

